version: "3.9"

services:
  api:
    image: sdc-api:latest
    container_name: sdc-api
    environment:
      - API_KEY=${API_KEY}
      - LOG_LEVEL=INFO
      - MAX_UPLOAD_BYTES=26214400
    networks: [sdcnet]
    restart: unless-stopped

  web:
    image: sdc-web:latest
    container_name: sdc-web
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on: [api]
    networks: [sdcnet]
    restart: unless-stopped
    ports:
      - "80:3000"

networks:
  sdcnet:
    driver: bridge
